services:
  postgres:
    image: postgres:17-alpine
    container_name: meal_planner_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./local_data/postgres_data:/var/lib/postgresql/data
    networks:
      - meal_planner_network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: meal_planner_admin
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - meal_planner_network

networks:
  meal_planner_network:
    driver: bridge

volumes:
  postgres_data:
