services:
  postgres:
    image: postgres:17-alpine
    container_name: meal_planner_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./local_data/postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - meal_planner_network

networks:
  meal_planner_network:
    driver: bridge

volumes:
  postgres_data:
