name: meal_planner
description: A meal planning application.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.2
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Routing
  go_router: ^13.0.1
  
  # Network and API
  dio: ^5.7.0
  json_annotation: ^4.9.0
  retrofit: ^4.0.3
  
  # Authentication
  firebase_core: ^2.25.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  
  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # UI Components
  flutter_hooks: ^0.20.3
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  
  # Utilities
  intl: ^0.19.0
  logger: ^2.0.2+1
  freezed_annotation: ^2.4.1
  uuid: ^4.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  retrofit_generator: ^8.0.6
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
        - asset: assets/fonts/Inter.ttf
          weight: 500
        - asset: assets/fonts/Inter.ttf
          weight: 600
        - asset: assets/fonts/Inter.ttf
          weight: 700
